### ISSUE TITLE
Can't start the mower

### ISSUE THREAD

**Issue by schlaubi79** [osks/hass-gardena-smart-system#17]
Hi,

many thanks for this integration, very much appreciated. I've unfortunately got an issue with starting the mower. Whenever I try to trigger the mower (play button), it fails with error 502. Note that I had the same issue with the previous fork that Tobias provided. 

Below my traceback data:

`502 : error communicating with the backend
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 213, in handle_service
    self._platforms.values(), func, call, required_features
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 454, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 597, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 485, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/vacuum/__init__.py", line 370, in async_start
    await self.hass.async_add_executor_job(self.start)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/gardena_smart_system/vacuum.py", line 170, in start
    self._device.start_seconds_to_override(duration)
  File "/srv/homeassistant/lib/python3.7/site-packages/gardena/devices/mower.py", line 30, in start_seconds_to_override
    self.smart_system.call_smart_system_service(self.id, data)
  File "/srv/homeassistant/lib/python3.7/site-packages/gardena/smart_system.py", line 135, in call_smart_system_service
    raise Exception(f"{r.status_code} : {response['errors'][0]['title']}")
Exception: 502 : error communicating with the backend`

Cheers

**Comment by thecem** [comment]
Gardena Gateway online?

**Comment by Jpsy** [comment]
Sorry, I can't reproduce that on my system:

![image](https://user-images.githubusercontent.com/1806058/83305879-d4f95b00-a201-11ea-928f-9be4b59a15b0.png)

**Comment by schlaubi79** [comment]
Yes my gateway is online.
I've also got the water control, which is working perfectly fine. The status of the mower is also reflected correctly, when it works per time plan or manually triggered via Gardena app.

Just triggering the mower to start cutting leads to the mentioned error. 

Btw, seems I am not the only one with this issue, see latest comment in the HA [thread](https://community.home-assistant.io/t/gardena-smart-system-home-assistant/51764/96): 
![image](https://user-images.githubusercontent.com/59670956/83306332-a8920e80-a202-11ea-9c03-649be9d2972e.png)

**Comment by northpower25** [comment]
I‘ve test the manual command with Sileno + (R160 Lic) and the newest firmware (10.19.00) for this and HA 0.110.3 and it workes fine for me. Have you Double checkt your mower firmware and your HA Version?

**Comment by osks** [comment]
Could you open an issue in the new repository (py-smart-gardena/hass-gardena-smart-system) and continue there please?
