### ISSUE TITLE
Unable to add Integration (version f1d5810)

### ISSUE THREAD

**Issue by Wictorssons** [osks/hass-gardena-smart-system#9]
Hi!

The component is added via HACS. When trying to add the Integration Gardena Smart System from the GUI, I enter E-mail, Password and Application Key / Client ID and press Submit. Immediately, the form is emptied.

I see the following in the home-assistant.log:

2020-05-26 16:33:33 ERROR (SyncWorker_9) [gardena.smart_system] 403 : {'message': 'Forbidden'}
2020-05-26 16:33:33 ERROR (MainThread) [custom_components.gardena_smart_system.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 70, in async_step_user
    user_input[CONF_CLIENT_ID])
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.7/site-packages/gardena/smart_system.py", line 157, in update_locations
    if len(response_data["data"]) < 1:
KeyError: 'data'

Any idea what I might have missed?

**Comment by thecem** [comment]
Did you restart HA? Which version of HA are you using?

**Comment by Wictorssons** [comment]
Yes, running 0.110.3.
I saw just now that the same behaviour was mentioned in the issue named "Can´t find the Integration".

**Comment by Wictorssons** [comment]
I made the same error as mentioned by bussio. I forgot to "Connect new API". After that it worked. Sorry about that! Closing this issue.
